apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
    argocd.argoproj.io/refresh: "hard"
spec:
  project: default
  source:
    - repoURL: 'https://github.com/pc-dae/observability-poc.git'
      targetRevision: main
      path: local-cluster/charts/namespaces
      helm:
        valueFiles:
        - $config/observability-cluster/config/cluster-params.yaml
    - repoURL: 'https://{{ .Values.github_server }}/{{ .Values.config_org }}/{{ .Values.config_repo }}.git'
      targetRevision: main
      ref: config
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
