apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-datasources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  project: default
  source:
    repoURL: 'https://github.com/pc-dae/observability-poc.git'
    targetRevision: main
    path: local-cluster/charts/grafana-datasources
    helm:
      valueFiles:
      - ../../config/cluster-params.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Replace=true
