apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: splunk-ingress
  namespace: splunk
  annotations:
    # Increase the body size for log uploads
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  ingressClassName: nginx
  rules:
  - host: splunk.{{ .Values.dnsSuffix }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: splunk-s1-standalone-service
            port:
              number: 8000 # Web UI
  - host: splunk-hec.{{ .Values.dnsSuffix }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: splunk-s1-standalone-service
            port:
              number: 8088 # HEC Data Port
  tls:
    - secretName: splunk-tls
      hosts:
        - splunk.{{ .Values.dnsSuffix }}
        - splunk-hec.{{ .Values.dnsSuffix }}