apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: splunk-test-secret
  namespace: splunk
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: splunk-test-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: splunk-test-secret
