apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-secrets-store
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts'
    chart: secrets-store-csi-driver
    targetRevision: 1.5.3
    helm:
      values: |
        hooks:
          crd-upgrade:
            enabled: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Replace=true
